### ISSUE TITLE
Typescript errors in 3.5.0

### ISSUE THREAD

**Issue by cslettengren** [jpkleemans/vite-svg-loader#67]
importing `@something/filename.svg?component` gives typescript error `TS2307: Cannot find module` in version 3.5.0. It works fine in 3.4.0.

Guessing it has something to do with the removed imports within the `*.svg?component` module.

![image](https://user-images.githubusercontent.com/419076/187916366-d819a5cc-84d8-4b07-b32f-5fcd8dfb5c00.png)

**Comment by jpkleemans** [comment]
Hi, thanks for pointing out! I've released the fix in [v3.5.1](https://github.com/jpkleemans/vite-svg-loader/releases/tag/3.5.1)

**Comment by cslettengren** [comment]
Thank you for a super fast fix!
